#!/usr/bin/env python3
"""Regenerate docs/MARKET_COMPARISON.md from the live performance model."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from sim.performance_benchmark import Workload, moire_summary, mode_assumptions, reference_platforms, latency_ms

OUT = ROOT / "docs" / "MARKET_COMPARISON.md"


def main() -> None:
    work = Workload("ResNet-50 (INT8)", 4.0)
    lines = [
        "# Market Comparison (Model-Derived)",
        "",
        "> **Evidence tier:** model rows only (not measured silicon).",
        "> Regenerated by `python scripts/update_market_comparison.py`.",
        "",
        f"Workload assumed: **{work.name}**, **{work.gops_per_inference:.1f} GOp / inference**.",
        "",
        "## Moire SoC modes",
        "",
        "| Config | Mode | TOPS | TOPS/W | Latency (ms) | Power (W) |",
        "|--------|------|------|--------|--------------|-----------|",
    ]
    for mode in ("physics_target", "conservative"):
        note = mode_assumptions(mode).note
        for label, vals in moire_summary(work, mode).items():
            lines.append(
                f"| {label} | {mode} | {vals['tops']:.1f} | {vals['tops_per_w']:.1f} | "
                f"{vals['latency_ms']:.2f} | {vals['power_w']:.1f} |"
            )
        lines.append(f"")
        lines.append(f"_Assumption ({mode}): {note}_")
        lines.append("")

    lines.extend(
        [
            "## Reference platforms (simplified model rows)",
            "",
            "| Platform | TOPS | TOPS/W | Latency (ms) | Power (W) |",
            "|----------|------|--------|--------------|-----------|",
        ]
    )
    for p in reference_platforms():
        lat = latency_ms(work.gops_per_inference, p.tops)
        lines.append(f"| {p.name} | {p.tops:g} | {p.tops_per_w:.1f} | {lat:.2f} | {p.power_w:g} |")

    lines.extend(
        [
            "",
            "## How to read this",
            "",
            "- Use **conservative** for planning and risk discussion.",
            "- Use **physics_target** as an optimistic research envelope.",
            "- Baseline platforms omit full memory/system accounting; treat as order-of-magnitude context.",
            "- Figures: `docs/generated/performance_comparison.png`",
            "",
            "See also: `docs/EVIDENCE_TIERS.md`, `docs/LIMITATIONS_AND_RESOLUTION_PLAN.md`.",
            "",
        ]
    )
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
